
import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Work_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { AuthProvider } from "@/context/AuthContext";
import "leaflet/dist/leaflet.css";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const PoppinsSans = Poppins({
  variable: "--font-poppins-sans",
  subsets: ["latin"],
  weight: ["200", "300", "500", "600", "700"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
  weight: ["200", "300", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.workSans} ${geistMono.variable} ${PoppinsSans.variable} antialiased bg-dark-background text-dark-foreground`}
      >

        <AuthProvider>

          <Navbar />
          {children}
          <Footer />
        </AuthProvider>


      </body>
    </html>
  );
}
